sudo: required

language: go

services:
  - docker

go:
  - 1.6.4
  - 1.7.4
  - 1.8rc1

# first part of the GOARCH workaround
# setting the GOARCH directly doesn't work, since the value will be overwritten later
# so set it to a temporary environment variable first
env:
  - TRAVIS_GOARCH=amd64 TESTMODE=unit
  - TRAVIS_GOARCH=amd64 TESTMODE=integration
  - TRAVIS_GOARCH=386 TESTMODE=unit
  - TRAVIS_GOARCH=386 TESTMODE=integration

# second part of the GOARCH workaround
# now actually set the GOARCH env variable to the value of the temporary variable set earlier
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export GOARCH=$TRAVIS_GOARCH
  - go env # for debugging

script:
  - .travis/script.sh

after_success:
  - .travis/after_success.sh
