dist: xenial
group: travis_latest

language: go

go:
  - "1.14.x"
  - "1.15.x"

# first part of the GOARCH workaround
# setting the GOARCH directly doesn't work, since the value will be overwritten later
# so set it to a temporary environment variable first
env:
  global:
    - TIMESCALE_FACTOR=20
  matrix:
    - TRAVIS_GOARCH=amd64 TESTMODE=unit
    - TRAVIS_GOARCH=amd64 TESTMODE=integration
    - TRAVIS_GOARCH=386 TESTMODE=unit
    - TRAVIS_GOARCH=386 TESTMODE=integration

# second part of the GOARCH workaround
# now actually set the GOARCH env variable to the value of the temporary variable set earlier
before_install:
  - travis_retry go get golang.org/x/tools/cmd/cover
  - travis_retry go get github.com/onsi/ginkgo/ginkgo
  - travis_retry go get github.com/onsi/gomega
  - export GOARCH=$TRAVIS_GOARCH
  - go env # for debugging
  - travis_retry go get -t ./...

script:
  - .travis/script.sh


after_success:
  - .travis/after_success.sh
