name: Build interop Docker image
on: 
  push:
    branches:
      - master
    tags:
      - 'v*'
  
jobs:
  interop:
    runs-on: ${{ fromJSON(vars['DOCKER_RUNNER_UBUNTU'] || '"ubuntu-latest"') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set tag name
        id: tag
        # Tagged releases won't be picked up by the interop runner automatically,
        # but they can be useful when debugging regressions.
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_OUTPUT;
            echo "gitref=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_OUTPUT;
          else
            echo 'tag=latest' | tee -a $GITHUB_OUTPUT;
            echo 'gitref=${{ github.sha }}' | tee -a $GITHUB_OUTPUT;
          fi
      - uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:interop"
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GITREF=${{ steps.tag.outputs.gitref }}
          tags: martenseemann/quic-go-interop:${{ steps.tag.outputs.tag }}
